"use client";
import Head from "next/head";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount, useBalance } from "wagmi";
import styles from "../styles/Home.module.css";
import { usdtToken } from "../constants/token";
import WriteContract from "../components/WriteContract";

const Home = () => {
  const { address } = useAccount();
  const { data: balance, isLoading } = useBalance({
    address: address,
    token: usdtToken,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Ethereum DApp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ textAlign: "center" }}>Wallet Management</h1>
        <ConnectButton />
        <div>
          <span>Your balance: </span>
          {isLoading ? (
            <span>Loading...</span>
          ) : (
            <span>
              {balance?.formatted} {balance?.symbol}
            </span>
          )}
        </div>
        <WriteContract />
      </main>
    </div>
  );
};

export default Home;
